version: '3.8'

services:
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn newspaper_project.wsgi -b 0.0.0.0:8000
    environment:
        - SECRET_KEY=django-insecure-82fe0_^x$$r33o7$$8n@*lb*t@=k-$$ozmt*4m=6=f5jdrl8xx!m8
        - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000